apiVersion: extensions/v1beta1
kind: Deployment                                          # 1
metadata:
  name: sa-frontend
spec:
  replicas: 2                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: sa-frontend                                  # 6
    spec:
      containers:
        - image: seppaleinen/sentiment-analysis-frontend
          imagePullPolicy: Always                         # 7
          name: sa-frontend
          env:
            - name: WEBAPP_URL
              value: "http://sa-web-app"
          ports:
            - containerPort: 80