version: "3"

services:
  sa-frontend:
    restart: always
    build: sa-frontend
    image: rinormaloku/sentiment-analysis-frontend
    environment:
      - WEBAPP_URL=http://192.168.99.100:8080
    ports:
      - "80:80"
    networks:
      - frontend

  sa-logic:
    restart: always
#    build: sa-logic
    image: rinormaloku/sentiment-analysis
    expose:
      - "5000"
    networks:
      - frontend

  sa-webapp:
    restart: always
#    build: sa-webapp
    image: rinormaloku/sentiment-analysis-web-app
    ports:
      - "8080:8080"
    networks:
      - frontend

networks:
  frontend: