version: "3"

services:
  sa-frontend:
    restart: always
    build: sa-frontend
    image: seppaleinen/sentiment-analysis-frontend
    environment:
      - WEBAPP_URL=http://localhost:8080
    depends_on:
      - sa-webapp
    ports:
      - "80:80"
    networks:
      - frontend

  sa-logic:
    restart: always
    build: sa-logic
    image: seppaleinen/sentiment-analysis
    environment:
      - FLASK_ENV=development
    ports:
      - "5000:5000"
    networks:
      - frontend

  sa-webapp:
    restart: always
    build: sa-webapp
    image: seppaleinen/sentiment-analysis-web-app
    environment:
      - SA_LOGIC_API_URL=http://sa-logic:5000
    depends_on:
      - sa-logic
    links:
      - sa-logic
    ports:
      - "8080:8080"
    networks:
      - frontend

networks:
  frontend: